# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c715bc03436f9ac1d027de031231d1705a65b5ecbfef2bc87f2319524e427b60ad6d4044d70e92b9668a9efd354ca226c82e89c3c60e18ac881655011c019563

test:
  secret_key_base: 477fc5e6f43bf467ded1b3cf6ad552dfbd29c10ce5fc42b99fd7f6fb4231f6aa1827955ac1fafd3f771f77a495518aaad68503b8182cc8cdc8486055e6e0094c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
